// Server-skill emission: SKILL.md seed (once) + references/tools.md (always regenerated).
import fs from "fs/promises";
import path from "path";

type Logger = (msg: string) => void;
const noop: Logger = () => {};

/**
 * Emit a server-scoped skill at `<skillsDir>/<server>-server/`.
 * `references/tools.md` is always regenerated from the live schema so the catalog
 * stays in sync. `SKILL.md` is seeded only on first generation so iterative
 * human/agent curation (workhorses, gotchas) survives subsequent runs.
 */
export async function generateServerSkill(
  serverName: string,
  tools: any[],
  instructions: string | undefined,
  skillsDir: string,
  log: Logger = noop
): Promise<void> {
  const skillName = `${serverName}-server`;
  const skillDir = path.join(skillsDir, skillName);
  const referencesDir = path.join(skillDir, "references");
  await fs.mkdir(referencesDir, { recursive: true });

  const toolsMd = renderToolCatalog(serverName, tools, instructions);
  await fs.writeFile(path.join(referencesDir, "tools.md"), toolsMd);
  log(`  Generated: ${skillName}/references/tools.md`);

  const skillPath = path.join(skillDir, "SKILL.md");
  try {
    await fs.access(skillPath);
    log(`  Skipped (already exists): ${skillName}/SKILL.md`);
  } catch {
    await fs.writeFile(skillPath, renderSkillSeed(serverName, tools.length));
    log(`  Seeded: ${skillName}/SKILL.md`);
  }
}

export function renderToolCatalog(
  serverName: string,
  tools: any[],
  instructions: string | undefined
): string {
  const lines: string[] = [];
  lines.push(`# ${serverName} tool catalog`);
  lines.push("");
  lines.push(
    `Auto-generated by \`mcp-wrappers generate\`. Do not edit by hand — changes will be overwritten on the next run.`
  );
  lines.push("");
  lines.push(
    `Wrapper files live in \`./servers/${serverName}/\`. Import with: \`import * as ${serverName} from './servers/${serverName}';\``
  );
  lines.push("");

  if (instructions) {
    lines.push("## Server instructions");
    lines.push("");
    lines.push(instructions.trim());
    lines.push("");
  }

  const destructive: string[] = [];
  const readOnly: string[] = [];
  const other: string[] = [];
  for (const tool of tools) {
    const ann = tool.annotations ?? {};
    if (ann.readOnlyHint === true) readOnly.push(tool.name);
    else if ((ann.destructiveHint ?? true) === true) destructive.push(tool.name);
    else other.push(tool.name);
  }

  lines.push("## Index");
  lines.push("");
  lines.push(`- Total tools: ${tools.length}`);
  lines.push(`- Read-only: ${readOnly.length}`);
  lines.push(`- Destructive (may modify state non-additively): ${destructive.length}`);
  lines.push(`- Other (writes, but additive only or unspecified): ${other.length}`);
  lines.push("");
  if (destructive.length > 0) {
    lines.push(
      "> **Caution:** destructive tools may perform irreversible state changes. Verify intent before calling."
    );
    lines.push("");
  }

  lines.push("## All tools");
  lines.push("");

  const sorted = [...tools].sort((a, b) => a.name.localeCompare(b.name));
  for (const tool of sorted) {
    const ann = tool.annotations ?? {};
    const localName = tool.name.replace(/^.*__/, "");
    const ro = ann.readOnlyHint ?? false;
    const destr = ann.destructiveHint ?? true;
    const idem = ann.idempotentHint ?? false;

    const tags: string[] = [];
    if (ro) tags.push("read-only");
    if (!ro && destr) tags.push("destructive");
    if (!ro && idem) tags.push("idempotent");
    const tagSuffix = tags.length > 0 ? ` _(${tags.join(", ")})_` : "";

    lines.push(`### \`${tool.name}\`${tagSuffix}`);
    lines.push("");
    if (tool.description) {
      lines.push(String(tool.description).trim());
      lines.push("");
    }

    const required = extractRequiredParams(tool.inputSchema);
    if (required.length > 0) {
      lines.push(`Required: ${required.map((r) => `\`${r}\``).join(", ")}`);
      lines.push("");
    } else if (
      tool.inputSchema &&
      Object.keys(tool.inputSchema.properties ?? {}).length > 0
    ) {
      lines.push("Required: _(none — all parameters optional)_");
      lines.push("");
    }

    lines.push(`Wrapper: \`./servers/${serverName}/${localName}.ts\` (full input/output types)`);
    lines.push("");
  }

  return lines.join("\n");
}

export function extractRequiredParams(inputSchema: any): string[] {
  if (!inputSchema || typeof inputSchema !== "object") return [];
  const req = inputSchema.required;
  if (!Array.isArray(req)) return [];
  return req.filter((r) => typeof r === "string");
}

export function renderSkillSeed(serverName: string, toolCount: number): string {
  return `---
name: ${serverName}-server
description: Use when the task involves the ${serverName} service — any operation that would call an MCP tool from the ${serverName} server. Indexes the ${toolCount} available tools under \`./servers/${serverName}/\` and surfaces server-level gotchas before the agent starts \`ls\`-ing wrappers blindly. Read \`references/tools.md\` for the full catalog with descriptions and behavior hints.
---

# ${serverName} server

Wrapper files live in \`./servers/${serverName}/\`. Import with:

\`\`\`typescript
import * as ${serverName} from './servers/${serverName}';
\`\`\`

For the full list of tools, their descriptions, and behavior hints (read-only / destructive / idempotent), read \`references/tools.md\`. That file is regenerated from the live MCP schema on every \`mcp-wrappers generate\` run, so it's always in sync.

## Workhorses

<!-- Curate by hand: the 5-10 tools you actually reach for most often.
     Example:
     - \`list_issues\` — paginated issue fetch; pair with code-side filtering
     - \`get_file_contents\` — single-file read; preferred over cloning
-->

## Gotchas

<!-- Add server-specific corrections here as you encounter them. Examples:
     - Default page size is 30; pass perPage=100 for fewer round trips
     - Tool X requires auth scope Y; without it the call returns 200 with empty data
-->

## Related skills

<!-- Cross-reference workflow skills that build on this server. Example:
     - \`github-issue-analyzer\` — pre-built workflow for analyzing repo issues
-->
`;
}
